Add environment setup script to docker file

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -49,8 +49,8 @@ RUN pip3 install --upgrade pip
 ## Dependency installation
 RUN pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
 RUN pip3 install open3d --ignore-installed PyYAML==3.13
-COPY ./package_apt.txt /
-COPY ./requirement_pip.txt /
+COPY ./requirement/package_apt.txt /
+COPY ./requirement/requirement_pip.txt /
 RUN apt update && xargs -a /package_apt.txt apt install -y
 RUN pip3 install -r /requirement_pip.txt
 RUN rm /package_apt.txt /requirement_pip.txt
@@ -66,6 +66,12 @@ RUN apt install -y ros-$ros1_distro-desktop-full
 RUN apt install -y python3-rosdep python3-rosinstall-generator python3-vcstool build-essential
  
 RUN echo "ROS $ros1_distro installed successfully"
+
+## Setup GA-DDPG
+COPY ./requirement/setup_repo.sh /
+RUN sh /setup_repo.sh
+RUN rm /setup_repo.sh
+RUN if [ -d "/usr/lib/python3/dist-packages/omg-0.0.0-py3.8-linux-x86_64.egg/" ]; then echo 'OMG python package build failed. Exiting.'; exit 1; fi
 
 ## setting
 RUN chown -R ${USER}:${USER} ${HOME}/
